version: '3'
services:
  db:
    # image: mysql:latest
    build: ./mysql
    container_name: vuln_db
    ports:
      - "3306:3306"
    env_file: .env
    environment:
      TZ: "Asia/Seoul"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ['CMD', 'mysqladmin', 'ping', '-h', 'localhost']
      interval: 10s
      timeout: 5s
      retries: 5
    restart: always
    networks:
      - vuln_hub_internal

  web:
    build: ./app
    container_name: vuln_web
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"
      - "80:8000"
    env_file: .env
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./app:/app
    environment:
      TZ: "Asia/Seoul"
    depends_on:
      db:
        condition: service_healthy
    restart: always
    networks:
      - vuln_hub_external
      - vuln_hub_internal

volumes:
  mysql_data:

networks:
  vuln_hub_external:
    external: true
  vuln_hub_internal:
    internal: true
